### PR TITLE
Hover effect and curor pointer for the our rockets part and nav bar

### PR DESCRIPTION
**Pull request by thesri**
I have added the effects mentioned as in Issue#3. under JWOC'24

### CODE REVIEW

**Comment by Jagroop2001** [comment]
https://github.com/Jagroop2001/AcmeRockets/issues/3

**Comment by thesri** [comment]
@Jagroop2001 please assign the jwoc tags for this

**Comment by thesri** [comment]
this PR is accepted right? @Jagroop2001

**Comment by Jagroop2001** [comment]
yes

**Pull request merged**
