### PR TITLE
Modified Rate us page

### PR DESCRIPTION
**Pull request by Surajit0573**
Title : Improve rate us section
Issue : #65 
Changes : 

[screen-capture (2).webm](https://github.com/Jagroop2001/AcmeRockets/assets/111490250/a47fe392-5d8e-4c08-8a08-1a6018a3316b)

### CODE REVIEW

**Comment by Jagroop2001** [comment]
Hi @Surajit0573  !!
 Border-radius is too much.
Please remove that.

**Comment by Surajit0573** [comment]
@Jagroop2001 , Done....

**Comment by Surajit0573** [comment]
image

**Comment by Jagroop2001** [comment]
It doesn't look good. 
You can redesign something like that : 
https://d1eipm3vz40hy0.cloudfront.net/images/feedback+form+template.png

**Comment by Surajit0573** [comment]
Hi @Jagroop2001, I apologize for the inconvenience, but I am currently occupied and cannot continue working on the issue.
 However, I have added a pop-up function and made some improvements to the "rate us" area which should enhance its appearance. Though I understand that you are not satisfied with the changes, could you please change the difficulty tag based on my current work and merge this pull request? If you have any further suggestions for improvement, you can always create a new issue. Thank you for your understanding and patience.

**Comment by Surajit0573** [comment]
> @Surajit0573 Sorry, but I can't merge this. I am closing this PR and will unassign you because I fully understand your situation.

Okey, Thank you.

**Pull request closed without merging**
