### PR TITLE
Maintained Fototer and added reponsiveness

### LINKED ISSUE #2: Footer Section Enhancement: Improved Navigation and Visual Appeal
Evaluate and streamline the existing footer navigation links for better clarity and ease of access. Ensure that the links are organized logically to enhance the user experience.
Consider adding relevant links to important pages or resources, such as FAQs, Terms of Service, or a Site Map. This can provide users with quick access to essential information. please assign me this under JWoC

### PR DESCRIPTION
**Pull request by NaveenChandraAdhikari**
Closes #2 

Screenshot from 2024-01-15 17-58-07

### CODE REVIEW

**Comment by Jagroop2001** [comment]
@NaveenChandraAdhikari  
Please resolve merge conflict

**Comment by NaveenChandraAdhikari** [comment]
> @NaveenChandraAdhikari Please resolve merge conflict

@Jagroop2001 now it's all clear

**Comment by Jagroop2001** [comment]
@NaveenChandraAdhikari , 
Please reformat and remove the formatting and linting issue. 
Because I am not able to check the actual changes that you have done.

**Comment by NaveenChandraAdhikari** [comment]
@Jagroop2001 i have added new pr

**Pull request closed without merging**
