### PR TITLE
created feedback page

### PR DESCRIPTION
**Pull request by thesri**
created feedback page under jwoc 2024, please check

### CODE REVIEW

**Comment by thesri** [comment]
> created feedback page under jwoc 2024, please check

image

**Comment by Jagroop2001** [comment]
@thesri , it doesn't looks good, I will provide you the reference

**Comment by thesri** [comment]
> @thesri , it doesn't looks good, I will provide you the reference

Okay

**Comment by Jagroop2001** [comment]
Something like that : https://d1eipm3vz40hy0.cloudfront.net/images/feedback+form+template.png

**Comment by thesri** [comment]
> Something like that : https://d1eipm3vz40hy0.cloudfront.net/images/feedback+form+template.png

Okay

**Comment by thesri** [comment]
> Something like that : https://d1eipm3vz40hy0.cloudfront.net/images/feedback+form+template.png

but we have a rate us page for that write??

**Comment by Jagroop2001** [comment]
Sorry @thesri , 
something like that : 
https://cdn.dribbble.com/users/2201975/screenshots/6507560/feedback_page.png?resize=400x0

**Comment by thesri** [comment]
> Sorry @thesri , 
> 
> something like that : 
> 
> https://cdn.dribbble.com/users/2201975/screenshots/6507560/feedback_page.png?resize=400x0

Okay I'll get back to you soon

**Pull request closed without merging**
