### PR TITLE
Now fixed index.html and style.css for footer

### LINKED ISSUE #2: Footer Section Enhancement: Improved Navigation and Visual Appeal
Evaluate and streamline the existing footer navigation links for better clarity and ease of access. Ensure that the links are organized logically to enhance the user experience.
Consider adding relevant links to important pages or resources, such as FAQs, Terms of Service, or a Site Map. This can provide users with quick access to essential information. please assign me this under JWoC

### PR DESCRIPTION
**Pull request by NaveenChandraAdhikari**
closes #2

### CODE REVIEW

**Comment by Jagroop2001** [comment]
@NaveenChandraAdhikari , please resolve this merge conflict.I can't merge or allocate point in sheet until this resolved.

**Comment by Jagroop2001** [comment]
@NaveenChandraAdhikari , are you still want to continue with this issue ? If I didn't get any response then I will assign this to someone else.

**Comment by NaveenChandraAdhikari** [comment]
> @NaveenChandraAdhikari , are you still want to continue with this issue ? If I didn't get any response then I will assign this to someone else.

NO I WANT TO I am fixingit

**Comment by NaveenChandraAdhikari** [comment]
> > @NaveenChandraAdhikari , are you still want to continue with this issue ? If I didn't get any response then I will assign this to someone else.
> 
@Jagroop2001 can you see it now


 ...i don't know why every time git generates the issue as the issue is only related to  syntaxing ,from my side footer is working properly

**Comment by Jagroop2001** [comment]
https://github.com/Jagroop2001/AcmeRockets/issues/2

**Comment by Jagroop2001** [comment]
It's merged now !!

**Pull request merged**
